(()=>{
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[\u064B-\u065F\u0670]/g,'').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[أإآ]/g,'ا').replace(/[\s_\-()./]/g,'').trim();
const centers={'15مايو':[29.851,31.335],'حلوان':[29.851,31.335],'المعادي':[29.968,31.265],'المقطم':[29.968,31.265],'مدينةنصر':[30.073,31.325],'مدينهنصر':[30.073,31.325],'مصرالجديدة':[30.073,31.325],'القاهرةالجديدة':[30.027,31.470],'التجمعالاول':[30.027,31.470],'التجمعالثالث':[30.027,31.470],'التجمعالخامس':[30.027,31.470],'الرحاب':[30.027,31.470],'الجيزة':[30.045,31.200],'جيزة':[30.045,31.200],'المهندسين':[30.045,31.200],'الدقي':[30.045,31.200],'الهرم':[29.994,31.170],'فيصل':[29.994,31.170],'العمرانية':[29.994,31.170],'6اكتوبر':[30.015,30.975],'الشيخزايد':[30.015,30.975],'الساحلالشمالي':[31.05,29.75],'الساحلالشمالى':[31.05,29.75]};
const wh=[29.8515,31.3505];
function run(){
 const detail=document.querySelector('#details tbody'); const rows=[...(detail?.querySelectorAll('tr')||[])]; if(!rows.length||rows[0].children.length<9)return;
 const groups=[];const gm=new Map();rows.forEach(tr=>{const c=[...tr.children].map(x=>x.textContent.trim());const area=c[1],order=c[2],customer=c[3],phone=c[4],address=c[5],sku=c[6],product=c[7],qty=Number(c[8])||0;if(!area)return;const k=norm(area);if(!gm.has(k))gm.set(k,{name:area,rows:[]});gm.get(k).rows.push({order,customer,phone,address,sku,product,qty})});gm.forEach(g=>groups.push(g));
 const zbox=document.getElementById('zones');if(zbox)zbox.innerHTML=groups.map((g,i)=>`<div class="zoneCard"><div class="zoneNum">${i+1}</div><div class="zoneTitle">${esc(g.name)}</div><div class="zoneMeta">Unique Orders: <b>${new Set(g.rows.map(r=>r.order).filter(Boolean)).size}</b> · QTY: <b>${g.rows.reduce((s,r)=>s+r.qty,0)}</b><br>Vehicle: <b>—</b></div></div>`).join('')||'<div class="empty">لا توجد بيانات</div>';
 const routes=document.getElementById('routes');if(routes)routes.innerHTML=groups.map((g,i)=>`<div class="routeCard"><div class="routeTop"><div class="routeNum">${i+1}</div><div><div class="routeTitle">${esc(g.name)}</div><div class="routeMeta">Orders: ${new Set(g.rows.map(r=>r.order).filter(Boolean)).size} · QTY: ${g.rows.reduce((s,r)=>s+r.qty,0)}</div></div><div class="routeVehicle">—</div></div><div class="routeMeta">${esc(g.name)}</div></div>`).join('')||'<div class="empty">لا توجد مناطق محملة حاليًا</div>';
 const tb=document.getElementById('follow');if(tb)tb.querySelectorAll('tr').forEach(tr=>{if(tr.children.length>=6){const a=tr.children[4].innerHTML,b=tr.children[5].innerHTML;tr.children[4].innerHTML=b;tr.children[5].innerHTML=a}});
 const mapEl=document.getElementById('map');if(!mapEl||typeof L==='undefined')return;try{if(window.__dynamicMap)window.__dynamicMap.remove()}catch(e){}mapEl.innerHTML='';const mp=L.map(mapEl).setView([30.02,31.30],10);window.__dynamicMap=mp;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(mp);const pts=[wh];L.marker(wh).addTo(mp).bindPopup('<b>0 · Warehouse</b><br>2B Warehouse · 15 May');groups.forEach((g,i)=>{let p=centers[norm(g.name)];if(!p)return;pts.push(p);const os=[...new Set(g.rows.map(r=>r.order).filter(Boolean))],ads=[...new Set(g.rows.map(r=>r.address).filter(Boolean))];L.marker(p).addTo(mp).bindPopup(`<b>${i+1} · ${esc(g.name)}</b><br>Orders: ${os.length}<br>${os.join(' · ')}<br><br>${ads.slice(0,8).map(esc).join('<br>')}`)});if(pts.length>1)L.polyline(pts,{weight:3,dashArray:'8 8',opacity:.85}).addTo(mp);mp.fitBounds(L.latLngBounds(pts).pad(.08));setTimeout(()=>mp.invalidateSize(),300)}
setTimeout(run,1800);setTimeout(run,3500);setTimeout(run,6000);new MutationObserver(()=>setTimeout(run,250)).observe(document.body,{subtree:true,childList:true});
})();