(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const norm=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[\u064B-\u065F\u0670]/g,'').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/[أإآ]/g,'ا').replace(/[\s_\-()./]/g,'').trim();
 const centers={'15مايو':[29.851,31.335],'حلوان':[29.851,31.335],'المعادي':[29.968,31.265],'المقطم':[29.968,31.265],'مدينةنصر':[30.073,31.325],'مدينهنصر':[30.073,31.325],'مصرالجديدة':[30.073,31.325],'القاهرةالجديدة':[30.027,31.470],'التجمعالاول':[30.027,31.470],'التجمعالثالث':[30.027,31.470],'التجمعالخامس':[30.027,31.470],'الرحاب':[30.027,31.470],'الجيزة':[30.045,31.200],'جيزة':[30.045,31.200],'المهندسين':[30.045,31.200],'الدقي':[30.045,31.200],'الهرم':[29.994,31.170],'فيصل':[29.994,31.170],'العمرانية':[29.994,31.170],'6اكتوبر':[30.015,30.975],'الشيخزايد':[30.015,30.975],'الساحلالشمالي':[31.05,29.75],'الساحلالشمالى':[31.05,29.75]};
 const warehouse=[29.8515,31.3505];
 const keys=(rows,words)=>{const ks=[...new Set(rows.flatMap(r=>Object.keys(r||{})))];return ks.find(k=>words.some(w=>norm(k).includes(norm(w))))};
 function run(){
  const rows=Array.isArray(window.D)?window.D:[]; if(!rows.length)return;
  const areaK=keys(rows,['area','region','zone','منطقه','المنطقة']); const orderK=keys(rows,['order','shipment','awb','بوليص','اوردر']); const skuK=keys(rows,['sku','itemcode','productcode','كودالصنف']); const productK=keys(rows,['product','item','description','المنتج','الصنف']); const qtyK=keys(rows,['qty','quantity','الكمية']); const latK=keys(rows,['latitude','lat','خطالعرض']); const lngK=keys(rows,['longitude','lng','lon','خطالطول']); const addrK=keys(rows,['address','العنوان']); const custK=keys(rows,['customer','client','العميل']); const phoneK=keys(rows,['phone','mobile','الهاتف','التليفون']); const fbK=keys(rows,['customerfeedback','feedback','note','notes','comment','remark','request','followup','ملاحظ','تعليق','طلبالعميل']);
  const unique=a=>[...new Set(a.map(x=>String(x??'').trim()).filter(Boolean))];
  const groups=[];const gm=new Map();rows.forEach(r=>{const a=areaK?String(r[areaK]??'').trim():'';if(!a)return;const n=norm(a);if(!gm.has(n))gm.set(n,{name:a,rows:[]});gm.get(n).rows.push(r)});gm.forEach(g=>groups.push(g));
  const tb=document.getElementById('follow'); if(tb){tb.innerHTML=rows.map(r=>`<tr><td>${esc(orderK?r[orderK]:'')}</td><td>${esc(custK?r[custK]:'')}</td><td>${esc(phoneK?r[phoneK]:'')}</td><td>${esc(areaK?r[areaK]:'')}</td><td>${esc(addrK?r[addrK]:'')}</td><td>${esc(fbK?r[fbK]:'')}</td></tr>`).join('')}
  const detail=document.querySelector('#details tbody');if(detail){detail.innerHTML=rows.map(r=>`<tr><td>${esc(areaK?r[areaK]:'')}</td><td>${esc(orderK?r[orderK]:'')}</td><td>${esc(custK?r[custK]:'')}</td><td>${esc(phoneK?r[phoneK]:'')}</td><td>${esc(addrK?r[addrK]:'')}</td><td>${esc(skuK?r[skuK]:'')}</td><td>${esc(productK?r[productK]:'')}</td><td>${esc(qtyK?r[qtyK]:'')}</td></tr>`).join('')}
  const mapEl=document.getElementById('map');if(!mapEl||typeof L==='undefined')return;try{if(window.__cleanMap)window.__cleanMap.remove()}catch(e){}mapEl.innerHTML='';const map=L.map(mapEl,{zoomControl:true});window.__cleanMap=map;L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);const pts=[warehouse];L.marker(warehouse).addTo(map).bindPopup('<b>Warehouse</b>');
  groups.forEach((g,i)=>{const gps=g.rows.map(r=>[Number(latK?r[latK]:NaN),Number(lngK?r[lngK]:NaN)]).filter(p=>Number.isFinite(p[0])&&Number.isFinite(p[1])&&p[0]>0&&p[1]>0);const p=gps.length?[gps.reduce((s,x)=>s+x[0],0)/gps.length,gps.reduce((s,x)=>s+x[1],0)/gps.length]:centers[norm(g.name)];if(!p)return;pts.push(p);const orders=unique(g.rows.map(r=>orderK?r[orderK]:''));L.marker(p).addTo(map).bindPopup(`<b>${esc(g.name)}</b><br>Orders: ${orders.length}<br>${orders.map(esc).join(' · ')}`);gps.forEach(q=>L.circleMarker(q,{radius:5,weight:2,fillOpacity:.9}).addTo(map).bindPopup(`<b>${esc(orderK?g.rows.find(r=>Number(r[latK])===q[0]&&Number(r[lngK])===q[1])?.[orderK]:'')}</b>`))});
  if(pts.length>1)L.polyline(pts,{weight:3,dashArray:'8 8',opacity:.85}).addTo(map);map.fitBounds(L.latLngBounds(pts).pad(.08));setTimeout(()=>map.invalidateSize(),300);setTimeout(()=>map.invalidateSize(),1000);
 }
 setTimeout(run,1000);setTimeout(run,2500);setTimeout(run,5000);
})();